//! Async and coroutine symbol representation.
//!
//! These symbols represent various async/await and coroutine-related
//! constructs generated by the Swift compiler.

use crate::helpers::NodeExt;
use crate::raw::{Node, NodeKind};
use crate::symbol::Symbol;
use crate::types::TypeRef;

/// A Swift async or coroutine symbol.
pub struct AsyncSymbol<'ctx> {
    raw: Node<'ctx>,
    inner: Option<Box<Symbol<'ctx>>>,
}

impl std::fmt::Debug for AsyncSymbol<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut s = f.debug_struct("AsyncSymbol");
        s.field("kind", &self.kind());
        if let Some(idx) = self.partial_index() {
            s.field("partial_index", &idx);
        }
        if let Some(inner) = &self.inner {
            s.field("inner", inner);
        }
        s.finish()
    }
}

impl<'ctx> AsyncSymbol<'ctx> {
    /// Create an AsyncSymbol from a raw node.
    pub fn new(raw: Node<'ctx>) -> Self {
        Self { raw, inner: None }
    }

    /// Create an AsyncSymbol with an inner symbol (for sibling patterns).
    pub fn with_inner(raw: Node<'ctx>, inner: Symbol<'ctx>) -> Self {
        Self {
            raw,
            inner: Some(Box::new(inner)),
        }
    }

    /// Get the underlying raw node.
    pub fn raw(&self) -> Node<'ctx> {
        self.raw
    }

    /// Get the kind of async symbol.
    pub fn kind(&self) -> AsyncSymbolKind {
        match self.raw.kind() {
            NodeKind::AsyncAwaitResumePartialFunction => AsyncSymbolKind::AwaitResumePartial,
            NodeKind::AsyncSuspendResumePartialFunction => AsyncSymbolKind::SuspendResumePartial,
            NodeKind::AsyncFunctionPointer => AsyncSymbolKind::FunctionPointer,
            NodeKind::CoroFunctionPointer => AsyncSymbolKind::CoroFunctionPointer,
            NodeKind::CoroutineContinuationPrototype => AsyncSymbolKind::ContinuationPrototype,
            _ => AsyncSymbolKind::Other,
        }
    }

    /// Get the partial index (for partial functions).
    pub fn partial_index(&self) -> Option<u64> {
        for child in self.raw.children() {
            if child.kind() == NodeKind::Number || child.kind() == NodeKind::Index {
                return child.index();
            }
        }
        None
    }

    /// Get the inner symbol being wrapped, if any.
    pub fn inner(&self) -> Option<&Symbol<'ctx>> {
        self.inner.as_deref()
    }

    /// Get the inner function being wrapped, if any.
    pub fn inner_function(&self) -> Option<crate::function::Function<'ctx>> {
        // Check inner symbol first
        if let Some(inner) = &self.inner {
            return inner.as_function().cloned();
        }
        // Fall back to checking children
        for child in self.raw.children() {
            if child.kind() == NodeKind::Function {
                return Some(crate::function::Function::new(child));
            }
        }
        None
    }

    /// Get the inner type, if any.
    pub fn inner_type(&self) -> Option<TypeRef<'ctx>> {
        self.raw.extract_type_ref()
    }
}

impl std::fmt::Display for AsyncSymbol<'_> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.raw)
    }
}

/// The kind of async or coroutine symbol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AsyncSymbolKind {
    /// Async await resume partial function.
    AwaitResumePartial,
    /// Async suspend resume partial function.
    SuspendResumePartial,
    /// Async function pointer.
    FunctionPointer,
    /// Coroutine function pointer.
    CoroFunctionPointer,
    /// Coroutine continuation prototype.
    ContinuationPrototype,
    /// Other async-related symbol.
    Other,
}

impl AsyncSymbolKind {
    /// Get a human-readable name for this async symbol kind.
    pub fn name(&self) -> &'static str {
        match self {
            AsyncSymbolKind::AwaitResumePartial => "async await resume partial function",
            AsyncSymbolKind::SuspendResumePartial => "async suspend resume partial function",
            AsyncSymbolKind::FunctionPointer => "async function pointer",
            AsyncSymbolKind::CoroFunctionPointer => "coroutine function pointer",
            AsyncSymbolKind::ContinuationPrototype => "coroutine continuation prototype",
            AsyncSymbolKind::Other => "async symbol",
        }
    }
}
